openapi: 3.0.0
info:
  title: InsightPortal - Top
  version: '1.0'
  contact:
    url: www.qualitytaskforce.com
  description: Endpoints related to Top marketshares
servers:
  - url: 'https://api.insightportal.io'
paths:
  testadvisor/top/desktopbrowsers/global:
    get:
      summary: Get global desktop browsers
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    marketPen:
                      type: number
              examples:
                example-1:
                  value:
                    - name: Chrome
                      marketPen: 63.962852
                    - name: Safari
                      marketPen: 12.952977
                    - name: Firefox
                      marketPen: 7.105454
                    - name: IE
                      marketPen: 4.402005
                    - name: Others
                      marketPen: 11.574989
      description: Retrieves the market shares of desktop browsers globally
      security:
        - BasicAuth: []
      operationId: '1'
    parameters: []
  testadvisor/top/mobileos:
    get:
      summary: Get top mobileOS
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    marketPen:
                      type: number
              examples:
                example-1:
                  value:
                    - name: Android
                      marketPen: 59.92334
                    - name: iOS
                      marketPen: 40.07126
      description: Retrieves market shares for Android and iOS globally
      security:
        - BasicAuth: []
      operationId: '2'
    parameters: []
  'testadvisor/top/devices/{limit}':
    parameters:
      - schema:
          type: number
        name: limit
        in: path
        required: true
        description: Between 0 and 100
    get:
      summary: Get global top devices
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    brand:
                      type: string
                    model:
                      type: string
                    marketPen:
                      type: number
              examples:
                example-1:
                  value:
                    - brand: Apple
                      model: iPhone 7
                      marketPen: 4.859173
                    - brand: Apple
                      model: iPhone 8
                      marketPen: 4.462529
                    - brand: Apple
                      model: iPhone X
                      marketPen: 3.479606
                    - brand: Apple
                      model: iPhone 6s
                      marketPen: 3.373906
                    - brand: Huawei
                      model: P20
                      marketPen: 3.062391
      description: Retrieves the devices with the highest marketshares globally.
      security:
        - BasicAuth: []
      operationId: '3'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: Basic
      description: '"Basic" followed by a username and password separated by a colon, encoded in Base64.'
