openapi: 3.0.0
info:
  title: InsightPortal - TestAdvisor
  version: '1.0'
  contact:
    url: www.qualitytaskforce.com
  description: Endpoints related to TestAdvisor
servers:
  - url: 'https://api.insightportal.io'
    description: InsightPortal API
paths:
  /testadvisor/countries:
    get:
      summary: Get countries
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                    name:
                      type: string
                    region_code:
                      type: string
              examples:
                Country List:
                  value:
                    - code: AU
                      name: Australia
                      region_code: OC
                    - code: AT
                      name: Austria
                      region_code: EU
                    - code: BH
                      name: Bahrain
                      region_code: AS
      description: Retreive a list of supported countries. Alphabetically ordered.
      security:
        - BasicAuth: []
      operationId: '1'
  /testadvisor/regions:
    get:
      summary: Get regions
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                Region List:
                  value:
                    - AS
                    - EU
                    - NA
                    - OC
                    - WWW
      description: 'Retrieves a list of supported regions. "WWW" is a special region containing all available regions and countries.'
      security:
        - BasicAuth: []
      operationId: '2'
  '/testadvisor/countriesbyregion/{region}':
    parameters:
      - schema:
          type: string
        name: region
        in: path
        required: true
        description: The code of the region to search
    get:
      summary: Get countries by region
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                    name:
                      type: string
                    region_code:
                      type: string
              examples:
                CountriesByRegion:
                  value:
                    - code: AT
                      name: Austria
                      region_code: EU
                    - code: BE
                      name: Belgium
                      region_code: EU
                    - code: BG
                      name: Bulgaria
                      region_code: EU
      description: Retrieves a list of countries for a specific region
      security:
        - BasicAuth: []
      operationId: '3'
  '/testadvisor/browsers/{code}':
    parameters:
      - schema:
          type: string
        name: code
        in: path
        required: true
        description: Code of the target country
    get:
      summary: Get browser market shares
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    browserName:
                      type: string
                    marketPen:
                      type: string
              examples:
                Browsers GB:
                  value:
                    - browserName: Chrome
                      marketPen: 57.74
                    - browserName: Safari
                      marketPen: 21.69
                    - browserName: Edge
                      marketPen: 8.21
                    - browserName: Firefox
                      marketPen: 6.39
                    - browserName: IE
                      marketPen: 4.83
                    - browserName: Opera
                      marketPen: 0.85
                    - browserName: Mozilla
                      marketPen: 0.16
                    - browserName: Pale Moon
                      marketPen: 0.11
      description: Retrieves browser market data for a single country for the current month. Ordered by market penetration in descending order.
      security:
        - BasicAuth: []
      operationId: '4'
  /testadvisor/browsers:
    post:
      summary: Browser market shares - Configurable
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      type: object
                      properties:
                        browserName:
                          type: string
                        marketPen:
                          type: number
                  - type: object
                    properties:
                      inCoverage:
                        type: array
                        items:
                          type: object
                          properties:
                            browserName:
                              type: string
                            marketPen:
                              type: number
                      outOfCoverage:
                        type: array
                        items:
                          type: object
                          properties:
                            browserName:
                              type: string
                            marketPen:
                              type: number
              examples:
                example-1:
                  value:
                    inCoverage:
                      - browserName: Chrome
                        marketPen: 58.38704
                    outOfCoverage:
                      - browserName: Firefox
                        marketPen: 12.12374
                      - browserName: IE
                        marketPen: 7.71988
                      - browserName: Safari
                        marketPen: 7.02518
                      - browserName: Edge
                        marketPen: 6.06429
                      - browserName: Others
                        marketPen: 5.04829
                      - browserName: Opera
                        marketPen: 3.63133
                example-2:
                  value:
                    - browserName: Chrome
                      marketPen: 58.38704
                    - browserName: Firefox
                      marketPen: 12.12374
                    - browserName: IE
                      marketPen: 7.71988
                    - browserName: Safari
                      marketPen: 7.02518
                    - browserName: Edge
                      marketPen: 6.06429
                    - browserName: Others
                      marketPen: 5.04829
                    - browserName: Opera
                      marketPen: 3.63133
            application/xml:
              schema:
                type: object
                properties: {}
            multipart/form-data:
              schema:
                type: object
                properties: {}
      description: Retrieves browser market data. Allows for various configurations.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                country_codes:
                  type: array
                  items:
                    type: string
                regions:
                  type: array
                  items:
                    type: string
                date:
                  type: string
                coverage:
                  type: number
                hide_out_of_coverage:
                  type: boolean
                threshold:
                  type: number
              required:
                - country_codes
                - regions
                - date
            examples:
              EU + USA:
                value:
                  country_codes:
                    - USA
                  regions:
                    - EU
                  date: '2019-09-01'
              'GB, CH, DE, and North America split coverage':
                value:
                  country_codes:
                    - GB
                    - CH
                    - DE
                  regions:
                    - NA
                  date: '2019-09-01'
                  coverage: 40
                  threshold: 0.1
              'GB, CH, DE, and North America hidden coverage':
                value:
                  country_codes:
                    - GB
                    - CH
                    - DE
                  regions:
                    - NA
                  date: '2019-09-01'
                  coverage: 40
                  hide_out_of_coverage: true
                  threshold: 0.1
        description: "Required Options:\n\n• `country_codes` - An Array of country codes.\\*\n\n• `regions` - An array of region codes.\\*\n\n• `date` - `YYYY-mm-DD`\n\n\\* At least one of `country_codes` and `regions` must be supplied. They can be used independently or together.\n\nOptional:\n\n• `coverage` - Splits the data returned into 2 arrays. `inCoverage` and `outOfCoverage`. A value of `40` would return the largest marketshares, summing to 40% in the `inCoverage` list and the rest would be contained in the `outOfCoverage` list.\n\n• `hide_out_of_coverage` - Used together with the `coverage` option, will hide the `outOfCoverage` list, returning only the `inCoverage` data.\n\n• `threshold` - A limit to cut off the data returned. A value of `0.5` will discard any marketshare data below 0.5"
      security:
        - BasicAuth: []
      operationId: '5'
      tags: []
  '/testadvisor/desktopbrowsers/{code}':
    parameters:
      - schema:
          type: string
        name: code
        in: path
        required: true
        description: Code of the target country
    get:
      summary: Get Desktop Browser Marketshares
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    osName:
                      type: string
                    osVersion:
                      type: string
                    browserName:
                      type: string
                    browserVersion:
                      type: string
                    marketPen:
                      type: number
              examples:
                example-1:
                  value:
                    - osName: Apple macOS
                      osVersion: ''
                      browserName: Safari
                      browserVersion: '12.1'
                      marketPen: 29.82
                    - osName: Microsoft
                      osVersion: Windows 10
                      browserName: Chrome
                      browserVersion: '78.0'
                      marketPen: 21.06
                    - osName: Microsoft
                      osVersion: Windows 10
                      browserName: Firefox
                      browserVersion: '69.0'
                      marketPen: 8.09
                    - osName: Microsoft
                      osVersion: Windows 10
                      browserName: Chrome
                      browserVersion: '77.0'
                      marketPen: 6.98
      description: Retrieves desktop browser and operating system market data for a single country for the current month. Ordered by market penetration in descending order.
      security:
        - BasicAuth: []
      operationId: '6'
  /testadvisor/desktopbrowsers/:
    post:
      summary: Desktop Browser Marketshares - Configurable
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      type: object
                      properties:
                        osName:
                          type: string
                        osVersion:
                          type: string
                        browserName:
                          type: string
                        browserVersion:
                          type: string
                        marketPen:
                          type: number
                  - type: object
                    properties:
                      inCoverage:
                        type: array
                        items:
                          type: object
                          properties:
                            osName:
                              type: string
                            osVersion:
                              type: string
                            browserName:
                              type: string
                            browserVersion:
                              type: string
                            marketPen:
                              type: number
                      outOfCoverage:
                        type: array
                        items:
                          type: object
                          properties:
                            osName:
                              type: string
                            osVersion:
                              type: string
                            browserName:
                              type: string
                            browserVersion:
                              type: string
                            marketPen:
                              type: number
              examples:
                example-1:
                  value:
                    inCoverage:
                      - osName: Apple macOS
                        osVersion: ''
                        browserName: Safari
                        browserVersion: '12.1'
                        marketPen: 29.82
                      - osName: Microsoft
                        osVersion: Windows 10
                        browserName: Chrome
                        browserVersion: '78.0'
                        marketPen: 21.06
                    outOfCoverage:
                      - osName: Microsoft
                        osVersion: Windows 10
                        browserName: Firefox
                        browserVersion: '69.0'
                        marketPen: 8.09
                      - osName: Microsoft
                        osVersion: Windows 10
                        browserName: Chrome
                        browserVersion: '77.0'
                        marketPen: 6.98
                example-2:
                  value:
                    - osName: Apple macOS
                      osVersion: ''
                      browserName: Safari
                      browserVersion: '12.1'
                      marketPen: 29.82
                    - osName: Microsoft
                      osVersion: Windows 10
                      browserName: Chrome
                      browserVersion: '78.0'
                      marketPen: 21.06
                    - osName: Microsoft
                      osVersion: Windows 10
                      browserName: Firefox
                      browserVersion: '69.0'
                      marketPen: 8.09
                    - osName: Microsoft
                      osVersion: Windows 10
                      browserName: Chrome
                      browserVersion: '77.0'
                      marketPen: 6.98
      description: Retrieves desktop browser and operating system market data. Allows for various configurations.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                country_codes:
                  type: array
                  items:
                    type: string
                regions:
                  type: array
                  items:
                    type: string
                date:
                  type: string
                coverage:
                  type: number
                hide_out_of_coverage:
                  type: boolean
                threshold:
                  type: number
        description: "Required Options:\n\n• `country_codes` - An Array of country codes.\\*\n\n• `regions` - An array of region codes.\\*\n\n• `date` - `YYYY-mm-DD`\n\n\\* At least one of `country_codes` and `regions` must be supplied. They can be used independently or together.\n\nOptional:\n\n• `coverage` - Splits the data returned into 2 arrays. `inCoverage` and `outOfCoverage`. A value of `40` would return the largest marketshares, summing to 40% in the `inCoverage` list and the rest would be contained in the `outOfCoverage` list.\n\n• `hide_out_of_coverage` - Used together with the `coverage` option, will hide the `outOfCoverage` list, returning only the `inCoverage` data.\n\n• `threshold` - A limit to cut off the data returned. A value of `0.5` will discard any marketshare data below 0.5"
      security:
        - BasicAuth: []
      operationId: '7'
      tags: []
    parameters: []
  '/testadvisor/mobiledevices/{code}':
    parameters:
      - schema:
          type: string
        name: code
        in: path
        required: true
        description: Code of the target country
    get:
      summary: Get Mobile Device Marketshares
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    brand:
                      type: string
                    model:
                      type: string
                    type:
                      type: string
                    osName:
                      type: string
                    osVersion:
                      type: string
                    marketPen:
                      type: number
              examples:
                example-1:
                  value:
                    - brand: Apple
                      model: iPhone 7 Plus
                      type: Smartphone
                      osName: iOS
                      osVersion: '11.2'
                      marketPen: 10.49
                    - brand: Apple
                      model: iPhone SE
                      type: Smartphone
                      osName: iOS
                      osVersion: '11.2'
                      marketPen: 6.06
                    - brand: Apple
                      model: iPhone 8
                      type: Smartphone
                      osName: iOS
                      osVersion: '11.2'
                      marketPen: 6
                    - brand: Apple
                      model: iPhone 6s
                      type: Smartphone
                      osName: iOS
                      osVersion: '11.2'
                      marketPen: 5.52
      description: Retrieves mobile device market data for the current month in the selected country. Ordered by market share
      security:
        - BasicAuth: []
      operationId: '8'
  /testadvisor/mobiledevices/:
    post:
      summary: Mobile Device Marketshares - Configurable
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      type: object
                      properties:
                        brand:
                          type: string
                        model:
                          type: string
                        type:
                          type: string
                        osName:
                          type: string
                        osVersion:
                          type: string
                        marketPen:
                          type: number
                  - type: object
                    properties:
                      inCoverage:
                        type: array
                        items:
                          type: object
                          properties:
                            brand:
                              type: string
                            model:
                              type: string
                            type:
                              type: string
                            osName:
                              type: string
                            osVersion:
                              type: string
                            marketPen:
                              type: number
                      outOfCoverage:
                        type: array
                        items:
                          type: object
                          properties:
                            brand:
                              type: string
                            model:
                              type: string
                            type:
                              type: string
                            osName:
                              type: string
                            osVersion:
                              type: string
                            marketPen:
                              type: number
              examples:
                example-1:
                  value:
                    inCoverage:
                      - brand: Apple
                        model: iPhone 7 Plus
                        type: Smartphone
                        osName: iOS
                        osVersion: '11.2'
                        marketPen: 10.49
                      - brand: Apple
                        model: iPhone SE
                        type: Smartphone
                        osName: iOS
                        osVersion: '11.2'
                        marketPen: 6.06
                    outOfCoverage:
                      - brand: Apple
                        model: iPhone 8
                        type: Smartphone
                        osName: iOS
                        osVersion: '11.2'
                        marketPen: 6
                      - brand: Apple
                        model: iPhone 6s
                        type: Smartphone
                        osName: iOS
                        osVersion: '11.2'
                        marketPen: 5.52
                example-2:
                  value:
                    - brand: Apple
                      model: iPhone 7 Plus
                      type: Smartphone
                      osName: iOS
                      osVersion: '11.2'
                      marketPen: 10.49
                    - brand: Apple
                      model: iPhone SE
                      type: Smartphone
                      osName: iOS
                      osVersion: '11.2'
                      marketPen: 6.06
                    - brand: Apple
                      model: iPhone 8
                      type: Smartphone
                      osName: iOS
                      osVersion: '11.2'
                      marketPen: 6
                    - brand: Apple
                      model: iPhone 6s
                      type: Smartphone
                      osName: iOS
                      osVersion: '11.2'
                      marketPen: 5.52
      description: Retrieves mobile device market data. Allows for various configurations.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '':
                  type: number
        description: "Required Options:\n\n• `country_codes` - An Array of country codes.\\*\n\n• `regions` - An array of region codes.\\*\n\n• `date` - `YYYY-mm-DD`\n\n\\* At least one of `country_codes` and `regions` must be supplied. They can be used independently or together.\n\nOptional:\n\n• `coverage` - Splits the data returned into 2 arrays. `inCoverage` and `outOfCoverage`. A value of `40` would return the largest marketshares, summing to 40% in the `inCoverage` list and the rest would be contained in the `outOfCoverage` list.\n\n• `hide_out_of_coverage` - Used together with the `coverage` option, will hide the `outOfCoverage` list, returning only the `inCoverage` data.\n\n• `threshold` - A limit to cut off the data returned. A value of `0.5` will discard any marketshare data below 0.5"
      security:
        - BasicAuth: []
      operationId: '9'
      tags: []
    parameters: []
  '/testadvisor/operatingsystems/{os}/{code}':
    parameters:
      - schema:
          type: string
        name: os
        in: path
        required: true
        description: '`iOS` or `Android`'
      - schema:
          type: string
        name: code
        in: path
        required: true
        description: Code of the target country
    get:
      summary: Get Mobile Operating System Marketshares
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    osVersion:
                      type: string
                    date:
                      type: string
                    marketPen:
                      type: number
              examples:
                example-1:
                  value:
                    - osVersion: Gingerbeard
                      date: '2016-09-30'
                      marketPen: 0.4
                    - osVersion: Marshmallow
                      date: '2016-09-30'
                      marketPen: 5.4
                    - osVersion: Jelly Bean
                      date: '2016-09-30'
                      marketPen: 5.7
                    - osVersion: Honeycomb
                      date: '2016-09-30'
                      marketPen: 6.7
                    - osVersion: KitKat
                      date: '2016-09-30'
                      marketPen: 40.7
      description: Retrieves operating system market data for the specified country and os.
      security:
        - BasicAuth: []
      operationId: '10'
  /testadvisor/operatingsystems/:
    post:
      summary: Mobile Operating System Marketshares - Configurable
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    osVersion:
                      type: string
                    date:
                      type: string
                    marketPen:
                      type: number
              examples:
                example-1:
                  value:
                    - osVersion: 10.X
                      date: '2018-10-01'
                      marketPen: 1
                    - osVersion: 7.X
                      date: '2018-10-01'
                      marketPen: 0.1
                    - osVersion: 12.X
                      date: '2018-10-01'
                      marketPen: 46.6
                    - osVersion: 5.X
                      date: '2018-10-01'
                      marketPen: 0.1
      description: Retrieves mobile operating system market data. Allows for various configurations.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                country_codes:
                  type: array
                  items:
                    type: string
                regions:
                  type: array
                  items:
                    type: string
                start_date:
                  type: string
                end_date:
                  type: string
                os:
                  type: string
                historic:
                  type: boolean
                predictive:
                  type: boolean
              required:
                - country_codes
                - regions
                - start_date
                - end_date
                - os
                - historic
                - predictive
        description: "Required Options:\n\n• `country_codes` - An Array of country codes.\\*\n\n• `regions` - An array of region codes.\\*\n\n• `start_date` - `YYYY-mm-DD`\n\n• `end_date` - `YYYY-mm-DD`\n\n• `os` - `iOS` or `Android`\n\n• `historic` - `true` or `false`. Whether to display historic results. If false, the `start_date` will be set to the current date.\n\n• `predictive` - `true` or `false` Whether to display predictive results. If false, the `end_date` will be set to the current date.\n\n\\* At least one of `country_codes` and `regions` must be supplied. They can be used independently or together."
      security:
        - BasicAuth: []
      operationId: '11'
      tags: []
    parameters: []
  '/testadvisor/deviceranking/{brand}/{model}':
    parameters:
      - schema:
          type: string
        name: brand
        in: path
        required: true
        description: Device Brand
      - schema:
          type: string
        name: model
        in: path
        required: true
        description: Device Model
    get:
      summary: Get global device ranking
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  last-item:
                    type: number
                  devices:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        brand:
                          type: string
                        model:
                          type: string
                        marketPen:
                          type: number
              examples:
                example-1:
                  value:
                    last-item: 1168
                    devices:
                      - id: 9
                        brand: Samsung
                        model: Galaxy S8 Plus
                        marketPen: 2.126073
                      - id: 10
                        brand: Apple
                        model: iPhone 5s
                        marketPen: 2.054206
                      - id: 11
                        brand: Samsung
                        model: Galaxy S6
                        marketPen: 1.77028
                      - id: 12
                        brand: Samsung
                        model: Galaxy Note 8
                        marketPen: 1.601279
                      - id: 13
                        brand: Samsung
                        model: Galaxy S7
                        marketPen: 1.505465
      description: Retrieves the device ranking in the global market share and surrounding devices. In the return body `last-item` is the id of the device with the smallest market share.
      security:
        - BasicAuth: []
      operationId: '12'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: Basic
      description: '"Basic" followed by a username and password separated by a colon, encoded in Base64. '
